
-- @SqlSnippetPriority 400
-- @SqlModuleOrdering 3

-- The following source code ("Code") may only be used in accordance with the terms
-- and conditions of the license agreement you have with IBM Corporation. The Code 
-- is provided to you on an "AS IS" basis, without warranty of any kind.  
-- SUBJECT TO ANY STATUTORY WARRANTIES WHICH CAN NOT BE EXCLUDED, IBM MAKES NO 
-- WARRANTIES OR CONDITIONS EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED 
-- TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A 
-- PARTICULAR PURPOSE, AND NON-INFRINGEMENT, REGARDING THE CODE. IN NO EVENT WILL 
-- IBM BE LIABLE TO YOU OR ANY PARTY FOR ANY DIRECT, INDIRECT, SPECIAL OR OTHER 
-- CONSEQUENTIAL DAMAGES FOR ANY USE OF THE CODE, INCLUDING, WITHOUT LIMITATION, 
-- LOSS OF, OR DAMAGE TO, DATA, OR LOST PROFITS, BUSINESS, REVENUE, GOODWILL, OR 
-- ANTICIPATED SAVINGS, EVEN IF IBM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH 
-- DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF 
-- INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY 
-- NOT APPLY TO YOU.



-- MDM_TODO: CDKWB0044I Review CDDWLCOLUMNTP LOCALE_SENSITIVE settings
-- MDM_TODO: CDKWB0043I You may need to add entries to the INTERNALTXNKEY table for any new transactions


-- Notes
-- MDM_TODO: CDKWB0046I Statements are placed in the generated SQL file when user changes are required.
-- 1. Edit the following SQL files following any associated instructions.
-- 2. Connect to the database.
-- 3. Run each SQL file as shown below and in the same order.
-- 			db2 -vf MDMNW_SETUP_DB2.sql
-- 			db2 -vf MDMNW_TRIGGERS_DB2.sql
-- 			db2 -vf MDMNW_CONSTRAINTS_DB2.sql
--			db2 -vf MDMNW_ERRORS_100_DB2.sql
-- 			db2 -vf MDMNW_MetaData_DB2.sql
-- 			db2 -vf CONFIG_XMLSERVICES_RESPONSE_DB2.sql
-- 			db2 -vf MDMNW_CODETABLES_DB2.sql
	
	--#SET TERMINATOR ;
	


----------------------------------------------
-- Component type
----------------------------------------------

INSERT INTO MDMDUSER.COMPONENTTYPE (COMPONENT_TYPE_ID, DWL_PROD_TP_CD, COMPON_TYPE_VALUE, COMPON_LONG_DESC, LAST_UPDATE_DT, COMPONENT_CLASS ) 
   VALUES ( 2000051, 1, 'MaintainNWPersonBusinessProxy', null, CURRENT_TIMESTAMP, null);
INSERT INTO MDMDUSER.COMPONENTTYPE (COMPONENT_TYPE_ID, DWL_PROD_TP_CD, COMPON_TYPE_VALUE, COMPON_LONG_DESC, LAST_UPDATE_DT, COMPONENT_CLASS ) 
   VALUES ( 2000218, 1, 'CompositeNWPersonBObj', null, CURRENT_TIMESTAMP, null);
INSERT INTO MDMDUSER.COMPONENTTYPE (COMPONENT_TYPE_ID, DWL_PROD_TP_CD, COMPON_TYPE_VALUE, COMPON_LONG_DESC, LAST_UPDATE_DT, COMPONENT_CLASS ) 
   VALUES ( 2000242, 1, 'XNWPersonNameBObjExt', null, CURRENT_TIMESTAMP, null);
INSERT INTO MDMDUSER.COMPONENTTYPE (COMPONENT_TYPE_ID, DWL_PROD_TP_CD, COMPON_TYPE_VALUE, COMPON_LONG_DESC, LAST_UPDATE_DT, COMPONENT_CLASS ) 
   VALUES ( 2001300, 1, 'XNWPersonBObjExt', null, CURRENT_TIMESTAMP, null);
INSERT INTO MDMDUSER.COMPONENTTYPE (COMPONENT_TYPE_ID, DWL_PROD_TP_CD, COMPON_TYPE_VALUE, COMPON_LONG_DESC, LAST_UPDATE_DT, COMPONENT_CLASS ) 
   VALUES ( 2001364, 1, 'XNWPartyAddressBObjExt', null, CURRENT_TIMESTAMP, null);
INSERT INTO MDMDUSER.COMPONENTTYPE (COMPONENT_TYPE_ID, DWL_PROD_TP_CD, COMPON_TYPE_VALUE, COMPON_LONG_DESC, LAST_UPDATE_DT, COMPONENT_CLASS ) 
   VALUES ( 2001438, 1, 'XNWAddressBObjExt', 'This address extension is for the unique addresses that MDM will hold, regardless of the usage type. For Address data instances by usage type, see TCRMPartyAddressBObj / xNWPartyAddressBObj objects types.', CURRENT_TIMESTAMP, null);
INSERT INTO MDMDUSER.COMPONENTTYPE (COMPONENT_TYPE_ID, DWL_PROD_TP_CD, COMPON_TYPE_VALUE, COMPON_LONG_DESC, LAST_UPDATE_DT, COMPONENT_CLASS ) 
   VALUES ( 2001528, 1, 'XNWContactMethodBObjExt', null, CURRENT_TIMESTAMP, null);

----------------------------------------------
-- Error messages
----------------------------------------------

   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2000054, 2000051, 'INSERR', 2000052, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2000244, 2000242, 'FVERR', 20, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2000267, 2000242, 'INSERR', 2000266, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2000271, 2000242, 'DELERR', 2000270, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2000275, 2000242, 'READERR', 2000274, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2000279, 2000242, 'UPDERR', 2000278, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001641, 2000242, 'DIERR', 2001640, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2000347, 2001300, 'DIERR', 2001354, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2000367, 2001300, 'DIERR', 2001357, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2000379, 2001300, 'DIERR', 2001359, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001302, 2001300, 'FVERR', 20, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001325, 2001300, 'INSERR', 2001324, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001329, 2001300, 'DELERR', 2001328, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001333, 2001300, 'READERR', 2001332, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001337, 2001300, 'UPDERR', 2001336, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001645, 2001300, 'DIERR', 2001644, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001665, 2001300, 'DIERR', 2001664, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001733, 2001300, 'DIERR', 2001732, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001366, 2001364, 'FVERR', 20, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001389, 2001364, 'INSERR', 2001388, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001393, 2001364, 'DELERR', 2001392, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001397, 2001364, 'READERR', 2001396, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001401, 2001364, 'UPDERR', 2001400, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001440, 2001438, 'FVERR', 20, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001463, 2001438, 'INSERR', 2001462, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001467, 2001438, 'DELERR', 2001466, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001471, 2001438, 'READERR', 2001470, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001475, 2001438, 'UPDERR', 2001474, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001685, 2001438, 'DIERR', 2001684, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001705, 2001438, 'DIERR', 2001704, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001709, 2001438, 'DIERR', 2001708, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001713, 2001438, 'DIERR', 2001712, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001530, 2001528, 'FVERR', 20, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001553, 2001528, 'INSERR', 2001552, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001557, 2001528, 'DELERR', 2001556, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001561, 2001528, 'READERR', 2001560, CURRENT_TIMESTAMP);
   
INSERT INTO MDMDUSER.ERRREASON (ERR_REASON_TP_CD, COMPONENT_TYPE_ID, ERR_TYPE_CD, ERR_MESSAGE_TP_CD, LAST_UPDATE_DT) 
   VALUES (2001565, 2001528, 'UPDERR', 2001564, CURRENT_TIMESTAMP);

---------------------------------------------
-- Metadata setup
---------------------------------------------

----------------------------------------------
-- Add records for the table columns for xNWPersonName
----------------------------------------------


INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000288, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSONNAME'), 'X_FULL_NAME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001257, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSONNAME'), 'X_DEGREE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001614, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSONNAME'), 'X_DEGREE_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001622, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSONNAME'), 'X_DEGREE_LAST_VERIFIED_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000289, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSONNAME'), 'X_FULL_NAME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001258, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSONNAME'), 'X_DEGREE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001615, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSONNAME'), 'X_DEGREE_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001623, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSONNAME'), 'X_DEGREE_LAST_VERIFIED_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');
----------------------------------------------
-- Add records for the table columns for xNWPerson
----------------------------------------------


INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001346, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_JOB_TITLE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000296, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_JOB_FAMILY', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000304, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_FULL_TIME_PART_TIME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000328, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_STANDARD_HOURS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000336, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_BUSINESS_UNIT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000344, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_HIRE_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'DATE');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000356, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_EMP_ROLE_STATUS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000364, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_REHIRE_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'DATE');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000376, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_TERMINATION_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'DATE');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000388, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_DEPARTMENT_ID', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000396, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_DEPARTMENT_NAME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000404, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_SERVICE_LINE_FIN_BUDGETARY', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001630, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_GENDER_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001638, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_GENDER_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001654, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_MARITAL_STATUS_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001662, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_MARSTAT_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001722, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_EMPLOYMENTDATA_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001730, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'PERSON'), 'X_EMPDATA_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001347, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_JOB_TITLE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000297, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_JOB_FAMILY', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000305, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_FULL_TIME_PART_TIME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000329, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_STANDARD_HOURS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000337, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_BUSINESS_UNIT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000345, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_HIRE_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'DATE');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000357, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_EMP_ROLE_STATUS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000365, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_REHIRE_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'DATE');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000377, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_TERMINATION_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'DATE');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000389, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_DEPARTMENT_ID', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000397, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_DEPARTMENT_NAME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000405, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_SERVICE_LINE_FIN_BUDGETARY', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001631, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_GENDER_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001639, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_GENDER_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001655, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_MARITAL_STATUS_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001663, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_MARSTAT_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001723, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_EMPLOYMENTDATA_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001731, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_PERSON'), 'X_EMPDATA_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');
----------------------------------------------
-- Add records for the table columns for xNWPartyAddress
----------------------------------------------


INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000624, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_PROVIDER_FACILITY_STAFF_CODE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000632, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_PROV_FACILITY_ACTIVE_STATUS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000696, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_PRIMARY_OFFICE_FLAG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000728, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_DEACTIVATION_FLAG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000736, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_PRIMARY_BILLING_LOC_FLAG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001493, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_CREDENTIAL_STATUS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001501, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_PROVIDER_STATUS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001525, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_SCHD_PRIM_FLG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001742, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_PHONE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001750, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_PHONE_EXT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001758, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_SECONDARY_PHONE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001766, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_SEC_PHONE_EXT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001774, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESSGROUP'), 'X_FAX', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000625, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_PROVIDER_FACILITY_STAFF_CODE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000633, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_PROV_FACILITY_ACTIVE_STATUS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000697, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_PRIMARY_OFFICE_FLAG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000729, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_DEACTIVATION_FLAG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000737, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_PRIMARY_BILLING_LOC_FLAG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001494, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_CREDENTIAL_STATUS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001502, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_PROVIDER_STATUS', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001526, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_SCHD_PRIM_FLG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001743, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_PHONE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001751, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_PHONE_EXT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001759, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_SECONDARY_PHONE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001767, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_SEC_PHONE_EXT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001775, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESSGROUP'), 'X_FAX', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');
----------------------------------------------
-- Add records for the table columns for xNWAddress
----------------------------------------------


INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001484, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_COUNTY', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000688, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_HOSPITAL', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000584, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_FACILITY_NAME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000592, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_FACILITY_CODE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000640, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_DEPARTMENT_CODE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000648, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_DEPARTMENT_DESCRIPTION', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000656, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_LOCATION_CODE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000664, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_LOCATION_DESCRIPTION', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000998, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_LOCATION_MNEMONIC', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001006, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_LOCATION_ID', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001022, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_LOCATION_NAME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000600, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_PHONE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001509, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_PHONE_EXT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000672, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_SECONDARY_PHONE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001517, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_SEC_PHONE_EXT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000608, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_FAX', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000616, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_TAX_ID_NUMBER', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000680, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_NEWPORT_KEY', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001582, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_DEACTIVATION_FLAG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001598, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_ACTIVATION_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001606, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_DEACTIVATION_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001674, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_TAX_ID_NUMBER_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001682, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_TAX_ID_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001694, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_NEWPORT_KEY_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001702, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'ADDRESS'), 'X_NEWPORT_KEY_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001485, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_COUNTY', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000689, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_HOSPITAL', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000585, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_FACILITY_NAME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000593, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_FACILITY_CODE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000641, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_DEPARTMENT_CODE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000649, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_DEPARTMENT_DESCRIPTION', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000657, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_LOCATION_CODE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000665, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_LOCATION_DESCRIPTION', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000999, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_LOCATION_MNEMONIC', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001007, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_LOCATION_ID', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001023, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_LOCATION_NAME', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000601, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_PHONE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001510, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_PHONE_EXT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000673, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_SECONDARY_PHONE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001518, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_SEC_PHONE_EXT', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000609, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_FAX', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000617, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_TAX_ID_NUMBER', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2000681, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_NEWPORT_KEY', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001583, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_DEACTIVATION_FLAG', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001599, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_ACTIVATION_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001607, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_DEACTIVATION_DATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001675, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_TAX_ID_NUMBER_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001683, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_TAX_ID_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001695, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_NEWPORT_KEY_SOURCE', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001703, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_ADDRESS'), 'X_NEWPORT_KEY_LASTVERIFIEDDATE', null, CURRENT_TIMESTAMP, null, 'N', 'TIMESTAMP');
----------------------------------------------
-- Add records for the table columns for xNWContactMethod
----------------------------------------------


INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001574, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'CONTACTMETHOD'), 'X_EXTENSION', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

INSERT INTO MDMDUSER.CDDWLCOLUMNTP (DWLCOLUMN_TP_CD, DWLTABLE_TP_CD, COLUMN_NAME, EXPIRY_DT, LAST_UPDATE_DT, DESCRIPTION, LOCALE_SENSITIVE, JDBC_TYPE)
VALUES (2001575, (SELECT t.DWLTABLE_TP_CD FROM MDMDUSER.CDDWLTABLETP t WHERE t.TABLE_NAME = 'H_CONTACTMETHOD'), 'X_EXTENSION', null, CURRENT_TIMESTAMP, null, 'N', 'VARCHAR');

----------------------------------------------
-- V_GROUP
----------------------------------------------

INSERT INTO MDMDUSER.V_GROUP (GROUP_NAME, APPLICATION, OBJECT_NAME, LAST_UPDATE_DT, SORTBY, ALIAS_NAME, PARENT_GRP_NAME ) 
  VALUES ('CompositeNWPersonBObj', 'TCRM', 'mdmnw.component.CompositeNWPersonBObj', CURRENT_TIMESTAMP, 'LAST_UPDATE_DT', null, null);
INSERT INTO MDMDUSER.V_GROUP (GROUP_NAME, APPLICATION, OBJECT_NAME, LAST_UPDATE_DT, SORTBY, ALIAS_NAME, PARENT_GRP_NAME ) 
  VALUES ('XNWPersonNameBObjExt', 'TCRM', 'mdmnw.component.XNWPersonNameBObjExt', CURRENT_TIMESTAMP, 'LAST_UPDATE_DT', 'PERSONNAME', null);
INSERT INTO MDMDUSER.V_GROUP (GROUP_NAME, APPLICATION, OBJECT_NAME, LAST_UPDATE_DT, SORTBY, ALIAS_NAME, PARENT_GRP_NAME ) 
  VALUES ('XNWPersonBObjExt', 'TCRM', 'mdmnw.component.XNWPersonBObjExt', CURRENT_TIMESTAMP, 'LAST_UPDATE_DT', 'PERSON', null);
INSERT INTO MDMDUSER.V_GROUP (GROUP_NAME, APPLICATION, OBJECT_NAME, LAST_UPDATE_DT, SORTBY, ALIAS_NAME, PARENT_GRP_NAME ) 
  VALUES ('XNWPartyAddressBObjExt', 'TCRM', 'mdmnw.component.XNWPartyAddressBObjExt', CURRENT_TIMESTAMP, 'LAST_UPDATE_DT', 'ADDRESSGROUP', null);
INSERT INTO MDMDUSER.V_GROUP (GROUP_NAME, APPLICATION, OBJECT_NAME, LAST_UPDATE_DT, SORTBY, ALIAS_NAME, PARENT_GRP_NAME ) 
  VALUES ('XNWAddressBObjExt', 'TCRM', 'mdmnw.component.XNWAddressBObjExt', CURRENT_TIMESTAMP, 'LAST_UPDATE_DT', 'ADDRESS', null);
INSERT INTO MDMDUSER.V_GROUP (GROUP_NAME, APPLICATION, OBJECT_NAME, LAST_UPDATE_DT, SORTBY, ALIAS_NAME, PARENT_GRP_NAME ) 
  VALUES ('XNWContactMethodBObjExt', 'TCRM', 'mdmnw.component.XNWContactMethodBObjExt', CURRENT_TIMESTAMP, 'LAST_UPDATE_DT', 'CONTACTMETHOD', null);

CREATE SEQUENCE MDMDUSER.GROUPDWLTABLE_ID_SEQ AS BIGINT START WITH 2000000 INCREMENT BY 1 MINVALUE 2000000 MAXVALUE 2009999 CACHE 10;

----------------------------------------------
-- Add attributes for entity type CompositeNWPerson to V_ELEMENT table
----------------------------------------------

INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('TCRMPersonBObj', 'CompositeNWPersonBObj', 'TCRM', 'TCRMPersonBObj', CURRENT_TIMESTAMP, 10, 'TCRM',  'TCRMPersonBObj', null, 1);
----------------------------------------------
-- Add attributes for entity type xNWPersonName to V_ELEMENT table
----------------------------------------------

INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XFull_Name', 'XNWPersonNameBObjExt', 'TCRM', 'XFull_Name', CURRENT_TIMESTAMP, 10, null,  null, 2000288, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDegree', 'XNWPersonNameBObjExt', 'TCRM', 'XDegree', CURRENT_TIMESTAMP, 20, null,  null, 2001257, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDegree_Source', 'XNWPersonNameBObjExt', 'TCRM', 'XDegree_Source', CURRENT_TIMESTAMP, 30, null,  null, 2001614, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDegree_LastVerifiedDate', 'XNWPersonNameBObjExt', 'TCRM', 'XDegree_LastVerifiedDate', CURRENT_TIMESTAMP, 40, null,  null, 2001622, 1);
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, APPLICATION, GROUP_NAME, ATTRIBUTE_NAME, COLUMN_NAME, FIELD_NAME, XML_TAG_NAME, EXPIRY_DT, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD)
 	SELECT E.ELEMENT_NAME, 'TCRM', 'XNWPersonNameBObjExt', E.ATTRIBUTE_NAME, E.COLUMN_NAME, E.FIELD_NAME, E.XML_TAG_NAME, E.EXPIRY_DT, CURRENT_TIMESTAMP, E.RESPONSE_ORDER, E.ELEMENTAPPNAME, E.ELEMENTGROUPNAME, E.DWLCOLUMN_TP_CD, E.CARDINALITY_TP_CD
 	FROM MDMDUSER.V_ELEMENT E
 	LEFT JOIN MDMDUSER.V_GROUP G
 		ON E.GROUP_NAME = G.GROUP_NAME
 	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMPersonNameBObj';
 	
INSERT INTO MDMDUSER.GROUPDWLTABLE (GROUP_DWLTABLE_ID, APPLICATION, GROUP_NAME, DWLTABLE_TP_CD, LAST_UPDATE_DT)
	SELECT NEXTVAL FOR MDMDUSER.GROUPDWLTABLE_ID_SEQ, 'TCRM', 'XNWPersonNameBObjExt', T.DWLTABLE_TP_CD, CURRENT_TIMESTAMP
	FROM MDMDUSER.GROUPDWLTABLE T
	JOIN MDMDUSER.V_GROUP G
		ON T.GROUP_NAME = G.GROUP_NAME
	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMPersonNameBObj';
----------------------------------------------
-- Add attributes for entity type xNWPerson to V_ELEMENT table
----------------------------------------------

INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XJob_Title', 'XNWPersonBObjExt', 'TCRM', 'XJob_Title', CURRENT_TIMESTAMP, 10, null,  null, 2001346, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XJob_Family', 'XNWPersonBObjExt', 'TCRM', 'XJob_Family', CURRENT_TIMESTAMP, 20, null,  null, 2000296, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XFullTime_PartTIme', 'XNWPersonBObjExt', 'TCRM', 'XFullTime_PartTIme', CURRENT_TIMESTAMP, 30, null,  null, 2000304, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XStandard_Hours', 'XNWPersonBObjExt', 'TCRM', 'XStandard_Hours', CURRENT_TIMESTAMP, 40, null,  null, 2000328, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XBusiness_Unit', 'XNWPersonBObjExt', 'TCRM', 'XBusiness_Unit', CURRENT_TIMESTAMP, 50, null,  null, 2000336, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XHire_Date', 'XNWPersonBObjExt', 'TCRM', 'XHire_Date', CURRENT_TIMESTAMP, 60, null,  null, 2000344, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XEmployee_Role_Status', 'XNWPersonBObjExt', 'TCRM', 'XEmployee_Role_Status', CURRENT_TIMESTAMP, 70, null,  null, 2000356, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XRehire_Date', 'XNWPersonBObjExt', 'TCRM', 'XRehire_Date', CURRENT_TIMESTAMP, 80, null,  null, 2000364, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XTermination_Date', 'XNWPersonBObjExt', 'TCRM', 'XTermination_Date', CURRENT_TIMESTAMP, 90, null,  null, 2000376, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDepartment_ID', 'XNWPersonBObjExt', 'TCRM', 'XDepartment_ID', CURRENT_TIMESTAMP, 100, null,  null, 2000388, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDepartment_Name', 'XNWPersonBObjExt', 'TCRM', 'XDepartment_Name', CURRENT_TIMESTAMP, 110, null,  null, 2000396, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XService_Line_Financial_Budgetary', 'XNWPersonBObjExt', 'TCRM', 'XService_Line_Financial_Budgetary', CURRENT_TIMESTAMP, 120, null,  null, 2000404, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XGender_Source', 'XNWPersonBObjExt', 'TCRM', 'XGender_Source', CURRENT_TIMESTAMP, 130, null,  null, 2001630, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XGender_LastVerifiedDate', 'XNWPersonBObjExt', 'TCRM', 'XGender_LastVerifiedDate', CURRENT_TIMESTAMP, 140, null,  null, 2001638, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XMaritalStatus_Source', 'XNWPersonBObjExt', 'TCRM', 'XMaritalStatus_Source', CURRENT_TIMESTAMP, 150, null,  null, 2001654, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XMaritalStatus_LastVerifiedDate', 'XNWPersonBObjExt', 'TCRM', 'XMaritalStatus_LastVerifiedDate', CURRENT_TIMESTAMP, 160, null,  null, 2001662, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XEmploymentData_Source', 'XNWPersonBObjExt', 'TCRM', 'XEmploymentData_Source', CURRENT_TIMESTAMP, 170, null,  null, 2001722, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XEmploymentData_LastVerifiedDate', 'XNWPersonBObjExt', 'TCRM', 'XEmploymentData_LastVerifiedDate', CURRENT_TIMESTAMP, 180, null,  null, 2001730, 1);
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, APPLICATION, GROUP_NAME, ATTRIBUTE_NAME, COLUMN_NAME, FIELD_NAME, XML_TAG_NAME, EXPIRY_DT, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD)
 	SELECT E.ELEMENT_NAME, 'TCRM', 'XNWPersonBObjExt', E.ATTRIBUTE_NAME, E.COLUMN_NAME, E.FIELD_NAME, E.XML_TAG_NAME, E.EXPIRY_DT, CURRENT_TIMESTAMP, E.RESPONSE_ORDER, E.ELEMENTAPPNAME, E.ELEMENTGROUPNAME, E.DWLCOLUMN_TP_CD, E.CARDINALITY_TP_CD
 	FROM MDMDUSER.V_ELEMENT E
 	LEFT JOIN MDMDUSER.V_GROUP G
 		ON E.GROUP_NAME = G.GROUP_NAME
 	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMPersonBObj';
 	
INSERT INTO MDMDUSER.GROUPDWLTABLE (GROUP_DWLTABLE_ID, APPLICATION, GROUP_NAME, DWLTABLE_TP_CD, LAST_UPDATE_DT)
	SELECT NEXTVAL FOR MDMDUSER.GROUPDWLTABLE_ID_SEQ, 'TCRM', 'XNWPersonBObjExt', T.DWLTABLE_TP_CD, CURRENT_TIMESTAMP
	FROM MDMDUSER.GROUPDWLTABLE T
	JOIN MDMDUSER.V_GROUP G
		ON T.GROUP_NAME = G.GROUP_NAME
	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMPersonBObj';
----------------------------------------------
-- Add attributes for entity type xNWPartyAddress to V_ELEMENT table
----------------------------------------------

INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XProvider_Facility_Staff_Code', 'XNWPartyAddressBObjExt', 'TCRM', 'XProvider_Facility_Staff_Code', CURRENT_TIMESTAMP, 10, null,  null, 2000624, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XProvider_Facility_Active_Status', 'XNWPartyAddressBObjExt', 'TCRM', 'XProvider_Facility_Active_Status', CURRENT_TIMESTAMP, 20, null,  null, 2000632, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XPrimary_Office_Flag', 'XNWPartyAddressBObjExt', 'TCRM', 'XPrimary_Office_Flag', CURRENT_TIMESTAMP, 30, null,  null, 2000696, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDeactivation_Flag', 'XNWPartyAddressBObjExt', 'TCRM', 'XDeactivation_Flag', CURRENT_TIMESTAMP, 40, null,  null, 2000728, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XPrimary_Billing_Location_Flag', 'XNWPartyAddressBObjExt', 'TCRM', 'XPrimary_Billing_Location_Flag', CURRENT_TIMESTAMP, 50, null,  null, 2000736, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XCredential_Status', 'XNWPartyAddressBObjExt', 'TCRM', 'XCredential_Status', CURRENT_TIMESTAMP, 60, null,  null, 2001493, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XProvider_Status', 'XNWPartyAddressBObjExt', 'TCRM', 'XProvider_Status', CURRENT_TIMESTAMP, 70, null,  null, 2001501, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XScheduling_Primary_Flag', 'XNWPartyAddressBObjExt', 'TCRM', 'XScheduling_Primary_Flag', CURRENT_TIMESTAMP, 80, null,  null, 2001525, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XPhone', 'XNWPartyAddressBObjExt', 'TCRM', 'XPhone', CURRENT_TIMESTAMP, 90, null,  null, 2001742, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XPhone_Ext', 'XNWPartyAddressBObjExt', 'TCRM', 'XPhone_Ext', CURRENT_TIMESTAMP, 100, null,  null, 2001750, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XSecondary_Phone', 'XNWPartyAddressBObjExt', 'TCRM', 'XSecondary_Phone', CURRENT_TIMESTAMP, 110, null,  null, 2001758, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XSec_Phone_Ext', 'XNWPartyAddressBObjExt', 'TCRM', 'XSec_Phone_Ext', CURRENT_TIMESTAMP, 120, null,  null, 2001766, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XFax', 'XNWPartyAddressBObjExt', 'TCRM', 'XFax', CURRENT_TIMESTAMP, 130, null,  null, 2001774, 1);
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, APPLICATION, GROUP_NAME, ATTRIBUTE_NAME, COLUMN_NAME, FIELD_NAME, XML_TAG_NAME, EXPIRY_DT, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD)
 	SELECT E.ELEMENT_NAME, 'TCRM', 'XNWPartyAddressBObjExt', E.ATTRIBUTE_NAME, E.COLUMN_NAME, E.FIELD_NAME, E.XML_TAG_NAME, E.EXPIRY_DT, CURRENT_TIMESTAMP, E.RESPONSE_ORDER, E.ELEMENTAPPNAME, E.ELEMENTGROUPNAME, E.DWLCOLUMN_TP_CD, E.CARDINALITY_TP_CD
 	FROM MDMDUSER.V_ELEMENT E
 	LEFT JOIN MDMDUSER.V_GROUP G
 		ON E.GROUP_NAME = G.GROUP_NAME
 	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMPartyAddressBObj';
 	
INSERT INTO MDMDUSER.GROUPDWLTABLE (GROUP_DWLTABLE_ID, APPLICATION, GROUP_NAME, DWLTABLE_TP_CD, LAST_UPDATE_DT)
	SELECT NEXTVAL FOR MDMDUSER.GROUPDWLTABLE_ID_SEQ, 'TCRM', 'XNWPartyAddressBObjExt', T.DWLTABLE_TP_CD, CURRENT_TIMESTAMP
	FROM MDMDUSER.GROUPDWLTABLE T
	JOIN MDMDUSER.V_GROUP G
		ON T.GROUP_NAME = G.GROUP_NAME
	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMPartyAddressBObj';
----------------------------------------------
-- Add attributes for entity type xNWAddress to V_ELEMENT table
----------------------------------------------

INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XCounty', 'XNWAddressBObjExt', 'TCRM', 'XCounty', CURRENT_TIMESTAMP, 10, null,  null, 2001484, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XHospital', 'XNWAddressBObjExt', 'TCRM', 'XHospital', CURRENT_TIMESTAMP, 20, null,  null, 2000688, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XFacility_Name', 'XNWAddressBObjExt', 'TCRM', 'XFacility_Name', CURRENT_TIMESTAMP, 30, null,  null, 2000584, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XFacility_Code', 'XNWAddressBObjExt', 'TCRM', 'XFacility_Code', CURRENT_TIMESTAMP, 40, null,  null, 2000592, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDepartment_Code', 'XNWAddressBObjExt', 'TCRM', 'XDepartment_Code', CURRENT_TIMESTAMP, 50, null,  null, 2000640, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDepartment_Description', 'XNWAddressBObjExt', 'TCRM', 'XDepartment_Description', CURRENT_TIMESTAMP, 60, null,  null, 2000648, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XLocation_Code', 'XNWAddressBObjExt', 'TCRM', 'XLocation_Code', CURRENT_TIMESTAMP, 70, null,  null, 2000656, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XLocation_Description', 'XNWAddressBObjExt', 'TCRM', 'XLocation_Description', CURRENT_TIMESTAMP, 80, null,  null, 2000664, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XLocation_Mnemonic', 'XNWAddressBObjExt', 'TCRM', 'XLocation_Mnemonic', CURRENT_TIMESTAMP, 90, null,  null, 2000998, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XLocation_ID', 'XNWAddressBObjExt', 'TCRM', 'XLocation_ID', CURRENT_TIMESTAMP, 100, null,  null, 2001006, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XLocation_Name', 'XNWAddressBObjExt', 'TCRM', 'XLocation_Name', CURRENT_TIMESTAMP, 110, null,  null, 2001022, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XPhone', 'XNWAddressBObjExt', 'TCRM', 'XPhone', CURRENT_TIMESTAMP, 120, null,  null, 2000600, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XPhone_Ext', 'XNWAddressBObjExt', 'TCRM', 'XPhone_Ext', CURRENT_TIMESTAMP, 130, null,  null, 2001509, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XSecondary_Phone', 'XNWAddressBObjExt', 'TCRM', 'XSecondary_Phone', CURRENT_TIMESTAMP, 140, null,  null, 2000672, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XSec_Phone_Ext', 'XNWAddressBObjExt', 'TCRM', 'XSec_Phone_Ext', CURRENT_TIMESTAMP, 150, null,  null, 2001517, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XFax', 'XNWAddressBObjExt', 'TCRM', 'XFax', CURRENT_TIMESTAMP, 160, null,  null, 2000608, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XTax_ID_Number', 'XNWAddressBObjExt', 'TCRM', 'XTax_ID_Number', CURRENT_TIMESTAMP, 170, null,  null, 2000616, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XNewport_Key', 'XNWAddressBObjExt', 'TCRM', 'XNewport_Key', CURRENT_TIMESTAMP, 180, null,  null, 2000680, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDeactivation_Flag', 'XNWAddressBObjExt', 'TCRM', 'XDeactivation_Flag', CURRENT_TIMESTAMP, 190, null,  null, 2001582, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XActivation_Date', 'XNWAddressBObjExt', 'TCRM', 'XActivation_Date', CURRENT_TIMESTAMP, 200, null,  null, 2001598, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XDeactivation_Date', 'XNWAddressBObjExt', 'TCRM', 'XDeactivation_Date', CURRENT_TIMESTAMP, 210, null,  null, 2001606, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XTax_ID_Number_Source', 'XNWAddressBObjExt', 'TCRM', 'XTax_ID_Number_Source', CURRENT_TIMESTAMP, 220, null,  null, 2001674, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XTax_ID_Number_LastVerifiedDate', 'XNWAddressBObjExt', 'TCRM', 'XTax_ID_Number_LastVerifiedDate', CURRENT_TIMESTAMP, 230, null,  null, 2001682, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XNewport_Key_Source', 'XNWAddressBObjExt', 'TCRM', 'XNewport_Key_Source', CURRENT_TIMESTAMP, 240, null,  null, 2001694, 1);
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XNewport_Key_LastVerifiedDate', 'XNWAddressBObjExt', 'TCRM', 'XNewport_Key_LastVerifiedDate', CURRENT_TIMESTAMP, 250, null,  null, 2001702, 1);
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, APPLICATION, GROUP_NAME, ATTRIBUTE_NAME, COLUMN_NAME, FIELD_NAME, XML_TAG_NAME, EXPIRY_DT, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD)
 	SELECT E.ELEMENT_NAME, 'TCRM', 'XNWAddressBObjExt', E.ATTRIBUTE_NAME, E.COLUMN_NAME, E.FIELD_NAME, E.XML_TAG_NAME, E.EXPIRY_DT, CURRENT_TIMESTAMP, E.RESPONSE_ORDER, E.ELEMENTAPPNAME, E.ELEMENTGROUPNAME, E.DWLCOLUMN_TP_CD, E.CARDINALITY_TP_CD
 	FROM MDMDUSER.V_ELEMENT E
 	LEFT JOIN MDMDUSER.V_GROUP G
 		ON E.GROUP_NAME = G.GROUP_NAME
 	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMAddressBObj';
 	
INSERT INTO MDMDUSER.GROUPDWLTABLE (GROUP_DWLTABLE_ID, APPLICATION, GROUP_NAME, DWLTABLE_TP_CD, LAST_UPDATE_DT)
	SELECT NEXTVAL FOR MDMDUSER.GROUPDWLTABLE_ID_SEQ, 'TCRM', 'XNWAddressBObjExt', T.DWLTABLE_TP_CD, CURRENT_TIMESTAMP
	FROM MDMDUSER.GROUPDWLTABLE T
	JOIN MDMDUSER.V_GROUP G
		ON T.GROUP_NAME = G.GROUP_NAME
	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMAddressBObj';
----------------------------------------------
-- Add attributes for entity type xNWContactMethod to V_ELEMENT table
----------------------------------------------

INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, GROUP_NAME, APPLICATION, ATTRIBUTE_NAME, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD) 
   VALUES ('XExtension', 'XNWContactMethodBObjExt', 'TCRM', 'XExtension', CURRENT_TIMESTAMP, 10, null,  null, 2001574, 1);
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENT (ELEMENT_NAME, APPLICATION, GROUP_NAME, ATTRIBUTE_NAME, COLUMN_NAME, FIELD_NAME, XML_TAG_NAME, EXPIRY_DT, LAST_UPDATE_DT, RESPONSE_ORDER, ELEMENTAPPNAME, ELEMENTGROUPNAME, DWLCOLUMN_TP_CD, CARDINALITY_TP_CD)
 	SELECT E.ELEMENT_NAME, 'TCRM', 'XNWContactMethodBObjExt', E.ATTRIBUTE_NAME, E.COLUMN_NAME, E.FIELD_NAME, E.XML_TAG_NAME, E.EXPIRY_DT, CURRENT_TIMESTAMP, E.RESPONSE_ORDER, E.ELEMENTAPPNAME, E.ELEMENTGROUPNAME, E.DWLCOLUMN_TP_CD, E.CARDINALITY_TP_CD
 	FROM MDMDUSER.V_ELEMENT E
 	LEFT JOIN MDMDUSER.V_GROUP G
 		ON E.GROUP_NAME = G.GROUP_NAME
 	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMContactMethodBObj';
 	
INSERT INTO MDMDUSER.GROUPDWLTABLE (GROUP_DWLTABLE_ID, APPLICATION, GROUP_NAME, DWLTABLE_TP_CD, LAST_UPDATE_DT)
	SELECT NEXTVAL FOR MDMDUSER.GROUPDWLTABLE_ID_SEQ, 'TCRM', 'XNWContactMethodBObjExt', T.DWLTABLE_TP_CD, CURRENT_TIMESTAMP
	FROM MDMDUSER.GROUPDWLTABLE T
	JOIN MDMDUSER.V_GROUP G
		ON T.GROUP_NAME = G.GROUP_NAME
	WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMContactMethodBObj';

DROP SEQUENCE MDMDUSER.GROUPDWLTABLE_ID_SEQ RESTRICT;

----------------------------------------------
-- V_ELEMENTATTRIBUTE
----------------------------------------------


CREATE SEQUENCE MDMDUSER.V_ELATTR_ID_SEQ AS BIGINT START WITH 2000000 INCREMENT BY 1 MINVALUE 2000000 MAXVALUE 2009999 CACHE 10;

INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, LAST_UPDATE_DT) 
   VALUES (NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, 102, 'TCRM', 'CompositeNWPersonBObj', 'TCRMPersonBObj', CURRENT_TIMESTAMP);
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, LAST_UPDATE_DT) 
   VALUES (NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, 100, 'TCRM', 'XNWPersonNameBObjExt', 'XDegree_LastVerifiedDate', CURRENT_TIMESTAMP);
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, EXPIRY_DT, LAST_UPDATE_DT)
   SELECT NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, A.ATTRIBUTE_TP_CD, 'TCRM', 'XNWPersonNameBObjExt', A.ELEMENT_NAME, A.EXPIRY_DT, CURRENT_TIMESTAMP
   FROM MDMDUSER.V_ELEMENTATTRIBUTE A
   LEFT JOIN MDMDUSER.V_GROUP G
   		ON A.GROUP_NAME = G.GROUP_NAME
   WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMPersonNameBObj' ;
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, LAST_UPDATE_DT) 
   VALUES (NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, 100, 'TCRM', 'XNWPersonBObjExt', 'XGender_LastVerifiedDate', CURRENT_TIMESTAMP);
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, LAST_UPDATE_DT) 
   VALUES (NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, 100, 'TCRM', 'XNWPersonBObjExt', 'XMaritalStatus_LastVerifiedDate', CURRENT_TIMESTAMP);
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, LAST_UPDATE_DT) 
   VALUES (NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, 100, 'TCRM', 'XNWPersonBObjExt', 'XEmploymentData_LastVerifiedDate', CURRENT_TIMESTAMP);
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, EXPIRY_DT, LAST_UPDATE_DT)
   SELECT NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, A.ATTRIBUTE_TP_CD, 'TCRM', 'XNWPersonBObjExt', A.ELEMENT_NAME, A.EXPIRY_DT, CURRENT_TIMESTAMP
   FROM MDMDUSER.V_ELEMENTATTRIBUTE A
   LEFT JOIN MDMDUSER.V_GROUP G
   		ON A.GROUP_NAME = G.GROUP_NAME
   WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMPersonBObj' ;
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, EXPIRY_DT, LAST_UPDATE_DT)
   SELECT NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, A.ATTRIBUTE_TP_CD, 'TCRM', 'XNWPartyAddressBObjExt', A.ELEMENT_NAME, A.EXPIRY_DT, CURRENT_TIMESTAMP
   FROM MDMDUSER.V_ELEMENTATTRIBUTE A
   LEFT JOIN MDMDUSER.V_GROUP G
   		ON A.GROUP_NAME = G.GROUP_NAME
   WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMPartyAddressBObj' ;
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, LAST_UPDATE_DT) 
   VALUES (NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, 100, 'TCRM', 'XNWAddressBObjExt', 'XActivation_Date', CURRENT_TIMESTAMP);
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, LAST_UPDATE_DT) 
   VALUES (NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, 100, 'TCRM', 'XNWAddressBObjExt', 'XDeactivation_Date', CURRENT_TIMESTAMP);
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, LAST_UPDATE_DT) 
   VALUES (NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, 100, 'TCRM', 'XNWAddressBObjExt', 'XTax_ID_Number_LastVerifiedDate', CURRENT_TIMESTAMP);
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, LAST_UPDATE_DT) 
   VALUES (NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, 100, 'TCRM', 'XNWAddressBObjExt', 'XNewport_Key_LastVerifiedDate', CURRENT_TIMESTAMP);
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, EXPIRY_DT, LAST_UPDATE_DT)
   SELECT NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, A.ATTRIBUTE_TP_CD, 'TCRM', 'XNWAddressBObjExt', A.ELEMENT_NAME, A.EXPIRY_DT, CURRENT_TIMESTAMP
   FROM MDMDUSER.V_ELEMENTATTRIBUTE A
   LEFT JOIN MDMDUSER.V_GROUP G
   		ON A.GROUP_NAME = G.GROUP_NAME
   WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMAddressBObj' ;
-- This SQL statement copies any meta data configuration from the entity type
-- being extended into the extension.  If no such meta data exists, this will
-- cause a warning which can be ignored when running the SQL.
INSERT INTO MDMDUSER.V_ELEMENTATTRIBUTE (V_ELEMENT_ATTRB_ID, ATTRIBUTE_TP_CD, APPLICATION, GROUP_NAME, ELEMENT_NAME, EXPIRY_DT, LAST_UPDATE_DT)
   SELECT NEXTVAL FOR MDMDUSER.V_ELATTR_ID_SEQ, A.ATTRIBUTE_TP_CD, 'TCRM', 'XNWContactMethodBObjExt', A.ELEMENT_NAME, A.EXPIRY_DT, CURRENT_TIMESTAMP
   FROM MDMDUSER.V_ELEMENTATTRIBUTE A
   LEFT JOIN MDMDUSER.V_GROUP G
   		ON A.GROUP_NAME = G.GROUP_NAME
   WHERE G.OBJECT_NAME = 'com.dwl.tcrm.coreParty.component.TCRMContactMethodBObj' ;
DROP SEQUENCE MDMDUSER.V_ELATTR_ID_SEQ RESTRICT;

----------------------------------------------
-- Transactions
----------------------------------------------


----------------------------------------------
-- CDBUSINESSTXTP
----------------------------------------------


INSERT INTO MDMDUSER.CDBUSINESSTXTP (BUSINESS_TX_TP_CD, NAME, DESCRIPTION, EXPIRY_DT, LAST_UPDATE_DT, TX_LOG_IND, TX_OBJECT_TP, DEPRECATED_SINCE, DWL_PROD_TP_CD, PARENT_BUSINESS_TX_TP_CD) 
   VALUES (2000042, 'MaintainNWPerson', null, null, CURRENT_TIMESTAMP, 'N', 'P', null, 1, null);


----------------------------------------------
-- CDINTERNALTXNTP
----------------------------------------------




----------------------------------------------
-- BUSINTERNALTXN
----------------------------------------------



----------------------------------------------
-- BUSINESSTXREQRESP
----------------------------------------------


  
INSERT INTO MDMDUSER.BUSINESSTXREQRESP (BUSTX_REQRESP_ID, BUSINESS_TX_TP_CD, APPLICATION, GROUP_NAME, REQ_RESP_IND, TX_PARAM_TP_CD, PARAM_NAME, PARAM_ORDER, LAST_UPDATE_USER, LAST_UPDATE_DT, COLLECTION_IND)
values (2000047, 2000042, 'TCRM', 'CompositeNWPersonBObj', 'I', null, null, 1, 'cusadmin', CURRENT_TIMESTAMP, null);

INSERT INTO MDMDUSER.BUSINESSTXREQRESP (BUSTX_REQRESP_ID, BUSINESS_TX_TP_CD, APPLICATION, GROUP_NAME, REQ_RESP_IND, TX_PARAM_TP_CD, PARAM_NAME, PARAM_ORDER, LAST_UPDATE_USER, LAST_UPDATE_DT, COLLECTION_IND)
values (2000048, 2000042, 'TCRM', 'CompositeNWPersonBObj', 'O', null, null, null, 'cusadmin', CURRENT_TIMESTAMP, 'N');
	    


----------------------------------------------
-- INTERNALTXREQRESP
----------------------------------------------


----------------------------------------------
-- GROUPTXMAP
----------------------------------------------



----------------------------------------------
-- TAIL setup
----------------------------------------------



INSERT INTO MDMDUSER.ASIDEFINITION (ASI_DEFINITION_ID, ASI_NAME, TRANSFORM_TP_CD, MAPPING_DEFN, ADAPTER_NAME, DESCRIPTION, START_DT, LAST_UPDATE_DT)
	VALUES (2000004, 'http://mdmnw/MDMNW/port', 1, 'com.ibm.mdm.asi.transformation.MDMDefaultWSReqTransformation', 'com.ibm.mdm.asi.MDMOperationalServicesRequestAdapter', 'WS request transform for MDMNW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO MDMDUSER.ASIDEFINITION (ASI_DEFINITION_ID, ASI_NAME, TRANSFORM_TP_CD, MAPPING_DEFN, ADAPTER_NAME, DESCRIPTION, START_DT, LAST_UPDATE_DT)
	VALUES (2000005, 'http://mdmnw/MDMNW/port', 2, 'com.ibm.mdm.asi.transformation.MDMDefaultWSRespTransformation', 'com.ibm.mdm.asi.MDMDefaultResponseAdapter', 'WS response transform for MDMNW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
