UPDATE CONFIGELEMENT SET VALUE=NULL, LAST_UPDATE_DT=CURRENT_TIMESTAMP WHERE NAME='/IBM/BusinessServices/PME/Person/PMEContextKeys';
DELETE CONFIGELEMENT WHERE ELEMENT_ID>=2000 AND ELEMENT_ID<=3999;
commit;
