ALTER TABLE MDMDUSER.SUSPECTAUGMENT DISABLE CONSTRAINT F1_SUSPA;
TRUNCATE TABLE MDMDUSER.SUSPECT;
TRUNCATE TABLE MDMDUSER.H_SUSPECT;
ALTER TABLE MDMDUSER.SUSPECTAUGMENT ENABLE CONSTRAINT F1_SUSPA;

ALTER TABLE MDMDUSER.ROLEIDENTIFIER DISABLE CONSTRAINT F2_ROLEI;
TRUNCATE TABLE MDMDUSER.IDENTIFIER;
TRUNCATE TABLE MDMDUSER.H_IDENTIFIER;
ALTER TABLE MDMDUSER.ROLEIDENTIFIER ENABLE CONSTRAINT F2_ROLEI;

TRUNCATE TABLE MDMDUSER.ADDRESSGROUP;
TRUNCATE TABLE MDMDUSER.H_ADDRESSGROUP;

TRUNCATE TABLE MDMDUSER.CONTACTMETHODGROUP;
TRUNCATE TABLE MDMDUSER.H_CONTACTMETHODGRO;

ALTER TABLE MDMDUSER.ADDRESSGROUP DISABLE CONSTRAINT F1_ADRGR;
ALTER TABLE MDMDUSER.CONTACTMETHODGROUP DISABLE CONSTRAINT F1_CNTMG;
ALTER TABLE MDMDUSER.ROLELOCATION DISABLE CONSTRAINT F2_ROLLO;
TRUNCATE TABLE MDMDUSER.LOCATIONGROUP;
TRUNCATE TABLE MDMDUSER.H_LOCATIONGROUP;
ALTER TABLE MDMDUSER.ADDRESSGROUP ENABLE CONSTRAINT F1_ADRGR;
ALTER TABLE MDMDUSER.CONTACTMETHODGROUP ENABLE CONSTRAINT F1_CNTMG;
ALTER TABLE MDMDUSER.ROLELOCATION ENABLE CONSTRAINT F2_ROLLO;

ALTER TABLE MDMDUSER.ADDRESSGROUP DISABLE CONSTRAINT F2_ADRGR;
ALTER TABLE MDMDUSER.PROPERTY DISABLE CONSTRAINT F1_PRPTY;
TRUNCATE TABLE MDMDUSER.ADDRESS;
TRUNCATE TABLE MDMDUSER.H_ADDRESS;
--ALTER TABLE MDMDUSER.ADDRESSGROUP ENABLE CONSTRAINT F2_ADRGR;
ALTER TABLE MDMDUSER.PROPERTY ENABLE CONSTRAINT F1_PRPTY;

TRUNCATE TABLE MDMDUSER.PERSONSEARCH;
TRUNCATE TABLE MDMDUSER.H_PERSONSEARCH;

ALTER TABLE MDMDUSER.PERSONSEARCH DISABLE CONSTRAINT F2_PERSR;
TRUNCATE TABLE MDMDUSER.PERSONNAME;
TRUNCATE TABLE MDMDUSER.H_PERSONNAME;
ALTER TABLE MDMDUSER.PERSONSEARCH ENABLE CONSTRAINT F2_PERSR;

ALTER TABLE MDMDUSER.CONTACTMETHODGROUP DISABLE CONSTRAINT F2_CNTMG;
ALTER TABLE MDMDUSER.PHONENUMBER DISABLE CONSTRAINT F1_PHONE;
TRUNCATE TABLE MDMDUSER.CONTACTMETHOD;
TRUNCATE TABLE MDMDUSER.H_CONTACTMETHOD;
ALTER TABLE MDMDUSER.CONTACTMETHODGROUP ENABLE CONSTRAINT F2_CNTMG;
ALTER TABLE MDMDUSER.PHONENUMBER ENABLE CONSTRAINT F1_PHONE;
	
ALTER TABLE MDMDUSER.PERSONNAME DISABLE CONSTRAINT F1_PERNA;
ALTER TABLE MDMDUSER.PERSONSEARCH DISABLE CONSTRAINT F1_PERSR;
TRUNCATE TABLE MDMDUSER.PERSON;
TRUNCATE TABLE MDMDUSER.H_PERSON;
ALTER TABLE MDMDUSER.PERSONNAME ENABLE CONSTRAINT F1_PERNA;
ALTER TABLE MDMDUSER.PERSONSEARCH ENABLE CONSTRAINT F1_PERSR;

TRUNCATE TABLE MDMDUSER.INACTIVATEDCONT;
TRUNCATE TABLE MDMDUSER.H_INACTIVATEDCONT;

TRUNCATE TABLE MDMDUSER.INACTIVECONTLINK;
TRUNCATE TABLE MDMDUSER.H_INACTIVECONTLINK;

TRUNCATE TABLE MDMDUSER.CONTEQUIV;
TRUNCATE TABLE MDMDUSER.H_CONTEQUIV;

ALTER TABLE MDMDUSER.CONTACT DISABLE CONSTRAINT F1_CONT;
ALTER TABLE MDMDUSER.LOCATIONGROUP DISABLE CONSTRAINT F1_LOCGR;
ALTER TABLE MDMDUSER.PERSON DISABLE CONSTRAINT F1_PERSO;
ALTER TABLE MDMDUSER.CONTEQUIV DISABLE CONSTRAINT F1_CONTE;
ALTER TABLE MDMDUSER.IDENTIFIER DISABLE CONSTRAINT F1_IDENT;
ALTER TABLE MDMDUSER.INACTIVATEDCONT DISABLE CONSTRAINT F1_INCON;
ALTER TABLE MDMDUSER.INACTIVECONTLINK DISABLE CONSTRAINT F1_INCOL;
ALTER TABLE MDMDUSER.INCOMESOURCE DISABLE CONSTRAINT F1_INCOM;
ALTER TABLE MDMDUSER.ORG DISABLE CONSTRAINT F1_ORG;
ALTER TABLE MDMDUSER.SUSPECT DISABLE CONSTRAINT F1_SUSPE;
ALTER TABLE MDMDUSER.SUSPECT DISABLE CONSTRAINT F2_SUSPE;
ALTER TABLE MDMDUSER.CONTRACTROLE DISABLE CONSTRAINT F1_CONRO;
ALTER TABLE MDMDUSER.CONTACTREL DISABLE CONSTRAINT F1_COTRE;
ALTER TABLE MDMDUSER.CONTACTREL DISABLE CONSTRAINT F2_COTRE;
ALTER TABLE MDMDUSER.CLAIMROLE DISABLE CONSTRAINT F2_CLROL;
ALTER TABLE MDMDUSER.PAYMENTSOURCE DISABLE CONSTRAINT F1_PAYSR;
ALTER TABLE MDMDUSER.CONTSUMMARY DISABLE CONSTRAINT F1_COSUM;
ALTER TABLE MDMDUSER.CONTMACROROLE DISABLE CONSTRAINT F1_COMAC;
ALTER TABLE MDMDUSER.CONTACTCDC DISABLE CONSTRAINT F1_CNCDC;
ALTER TABLE MDMDUSER.CONTACTDEMOGRAPHICS DISABLE CONSTRAINT F1_CONTA;
TRUNCATE TABLE MDMDUSER.CONTACT;
TRUNCATE TABLE MDMDUSER.H_CONTACT;
ALTER TABLE MDMDUSER.CONTACT ENABLE CONSTRAINT F1_CONT;
ALTER TABLE MDMDUSER.LOCATIONGROUP ENABLE CONSTRAINT F1_LOCGR;
ALTER TABLE MDMDUSER.PERSON ENABLE CONSTRAINT F1_PERSO;
ALTER TABLE MDMDUSER.CONTEQUIV ENABLE CONSTRAINT F1_CONTE;
ALTER TABLE MDMDUSER.IDENTIFIER ENABLE CONSTRAINT F1_IDENT;
ALTER TABLE MDMDUSER.INACTIVATEDCONT ENABLE CONSTRAINT F1_INCON;
ALTER TABLE MDMDUSER.INACTIVECONTLINK ENABLE CONSTRAINT F1_INCOL;
ALTER TABLE MDMDUSER.INCOMESOURCE ENABLE CONSTRAINT F1_INCOM;
ALTER TABLE MDMDUSER.ORG ENABLE CONSTRAINT F1_ORG;
ALTER TABLE MDMDUSER.SUSPECT ENABLE CONSTRAINT F1_SUSPE;
ALTER TABLE MDMDUSER.SUSPECT ENABLE CONSTRAINT F2_SUSPE;
ALTER TABLE MDMDUSER.CONTRACTROLE ENABLE CONSTRAINT F1_CONRO;
ALTER TABLE MDMDUSER.CONTACTREL ENABLE CONSTRAINT F1_COTRE;
ALTER TABLE MDMDUSER.CONTACTREL ENABLE CONSTRAINT F2_COTRE;
ALTER TABLE MDMDUSER.CLAIMROLE ENABLE CONSTRAINT F2_CLROL;
ALTER TABLE MDMDUSER.PAYMENTSOURCE ENABLE CONSTRAINT F1_PAYSR;
ALTER TABLE MDMDUSER.CONTSUMMARY ENABLE CONSTRAINT F1_COSUM;
ALTER TABLE MDMDUSER.CONTMACROROLE ENABLE CONSTRAINT F1_COMAC;
ALTER TABLE MDMDUSER.CONTACTCDC ENABLE CONSTRAINT F1_CNCDC;
ALTER TABLE MDMDUSER.CONTACTDEMOGRAPHICS ENABLE CONSTRAINT F1_CONTA;

TRUNCATE TABLE MDMDUSER.MISCVALUE;
TRUNCATE TABLE MDMDUSER.H_MISCVALUE;

TRUNCATE TABLE MDMDUSER.EME_RECBKTD;
TRUNCATE TABLE MDMDUSER.EME_RECCMPD;
TRUNCATE TABLE MDMDUSER.EME_RECHEAD;
TRUNCATE TABLE MDMDUSER.EME_RECCHKD;

TRUNCATE TABLE MDMDUSER.MPI_PERSPECIALTY;
TRUNCATE TABLE MDMDUSER.MPI_PERRACE;
TRUNCATE TABLE MDMDUSER.MPI_PERPHONE;
TRUNCATE TABLE MDMDUSER.MPI_PERNAME;
TRUNCATE TABLE MDMDUSER.MPI_PERMARITAL;
TRUNCATE TABLE MDMDUSER.MPI_PERMANAGER;
TRUNCATE TABLE MDMDUSER.MPI_PERIDENT;
TRUNCATE TABLE MDMDUSER.MPI_PERGENDER;
TRUNCATE TABLE MDMDUSER.MPI_PERETHNICITY;
TRUNCATE TABLE MDMDUSER.MPI_PEREMAIL;
TRUNCATE TABLE MDMDUSER.MPI_PERDATE;
TRUNCATE TABLE MDMDUSER.MPI_PERBANK;
TRUNCATE TABLE MDMDUSER.MPI_PERATTREXT;
TRUNCATE TABLE MDMDUSER.MPI_PERADDR;
TRUNCATE TABLE MDMDUSER.MPI_MEMTAXONOMY;
TRUNCATE TABLE MDMDUSER.MPI_MEMBILLHIER;
TRUNCATE TABLE MDMDUSER.MPI_MEMHEAD;
TRUNCATE TABLE MDMDUSER.MPI_MEMCMPD;
TRUNCATE TABLE MDMDUSER.MPI_MEMBKTD;
TRUNCATE TABLE MDMDUSER.MPI_MEMXTSK;
TRUNCATE TABLE MDMDUSER.MPI_ENTLINK_MDMPER;
TRUNCATE TABLE MDMDUSER.MPI_ENTXEIA_MDMPER;
TRUNCATE TABLE MDMDUSER.MPI_ENTXTSK_MDMPER;

COMMIT;
