
  CREATE OR REPLACE VIEW SAMPLE_PAIRS ("SUSPECT_ID", "WEIGHT", "CONT_ID", "SOURCES", "X_FULL_NAME", "PREFIX", "GIVEN_NAME_ONE", "GIVEN_NAME_TWO", "LAST_NAME", "GENDER_TP_CODE", "BIRTH_DT", "NPI", "SSN", "ADDR_LINE_ONE", "ADDR_LINE_TWO", "CITY_NAME", "STATE", "POSTAL_CODE", "HOMEPHONE", "BUSINESS_EMAIL", "DRIVERS_LIC", "STLICS", "EMP_ID", "UNIV_ID", "UPIN", "LINEBREAKER", "SUSPECT_ID_2", "WEIGHT_2", "SUSPECT_CONT_ID", "SUS_SOURCES", "SUS_FULL_NAME", "SUS_PREFIX", "SUS_GIVEN_NAME_ONE", "SUS_GIVEN_NAME_TWO", "SUS_LAST_NAME", "SUS_GENDER_TP_CODE", "SUS_BIRTH_DT", "SUS_NPI", "SUS_SSN", "SUS_ADDR_LINE_ONE", "SUS_ADDR_LINE_TWO", "SUS_CITY_NAME", "SUS_STATE", "SUS_POSTAL_CODE", "SUS_HOMEPHONE", "SUS_BUSINESS_EMAIL", "SUS_DRIVERS_LIC", "SUS_STLICS", "SUS_EMP_ID", "SUS_UNIV_ID", "SUS_UPIN") AS 
  SELECT S.SUSPECT_ID AS SUSPECT_ID, S.WEIGHT AS WEIGHT, S.CONT_ID AS CONT_ID, 

CE.SOURCES, PN.X_FULL_NAME, PFXCD.NAME AS PREFIX, PN.GIVEN_NAME_ONE, PN.GIVEN_NAME_TWO, PN.LAST_NAME, PER.GENDER_TP_CODE,  
to_char(PER.BIRTH_DT , 'DD-MON-YYYY') AS BIRTH_DT, NPI.REF_NUM AS NPI, SSN.REF_NUM AS SSN, 
ADDRESS.ADDR_LINE_ONE, ADDRESS.ADDR_LINE_TWO, ADDRESS.CITY_NAME, ADDRESS.STATE, ADDRESS.POSTAL_CODE, HOMEPHONE.HOMEPHONE, BUSINESS_EMAIL.BUSINESS_EMAIL,
DL.REF_NUM AS DRIVERS_LIC, STLICS.STLICS, EMP_ID.REF_NUM AS EMP_ID, UNIV_ID.REF_NUM AS UNIV_ID, UPIN.REF_NUM AS UPIN,

'--LINE_BREAK_HERE--' AS LINEBREAKER,S.SUSPECT_ID AS SUSPECT_ID_2, S.WEIGHT AS WEIGHT_2, S.SUSPECT_CONT_ID AS SUSPECT_CONT_ID,

CE_SUS.SOURCES AS SUS_SOURCES, PN_SUS.X_FULL_NAME AS SUS_FULL_NAME, PFXCD_SUS.NAME AS SUS_PREFIX, PN_SUS.GIVEN_NAME_ONE AS SUS_GIVEN_NAME_ONE, PN_SUS.GIVEN_NAME_TWO AS SUS_GIVEN_NAME_TWO, 
PN_SUS.LAST_NAME AS SUS_LAST_NAME, PER_SUS.GENDER_TP_CODE AS SUS_GENDER_TP_CODE,  
to_char(PER_SUS.BIRTH_DT , 'DD-MON-YYYY') AS SUS_BIRTH_DT, NPI_SUS.REF_NUM AS SUS_NPI, SSN_SUS.REF_NUM AS SUS_SSN, 
ADDRESS_SUS.ADDR_LINE_ONE AS SUS_ADDR_LINE_ONE, ADDRESS_SUS.ADDR_LINE_TWO AS SUS_ADDR_LINE_TWO,
ADDRESS_SUS.CITY_NAME AS SUS_CITY_NAME, ADDRESS_SUS.STATE AS SUS_STATE, ADDRESS_SUS.POSTAL_CODE AS SUS_POSTAL_CODE, HOMEPHONE_SUS.HOMEPHONE AS SUS_HOMEPHONE, BUSINESS_EMAIL_SUS.BUSINESS_EMAIL AS SUS_BUSINESS_EMAIL,
DL_SUS.REF_NUM AS SUS_DRIVERS_LIC, STLICS_SUS.STLICS AS SUS_STLICS, EMP_ID_SUS.REF_NUM AS SUS_EMP_ID, UNIV_ID_SUS.REF_NUM AS SUS_UNIV_ID, UPIN_SUS.REF_NUM AS SUS_UPIN


FROM SUSPECT S


INNER JOIN 
(select CONT_ID, listagg(SRC.NAME || ':' ||CE.ADMIN_CLIENT_ID,',') within group( order by SRC.NAME || ':' ||CE.ADMIN_CLIENT_ID ) AS SOURCES
  from CONTEQUIV CE
  INNER JOIN CDADMINSYSTP SRC
  ON CE.ADMIN_SYS_TP_CD = SRC.ADMIN_SYS_TP_CD
  group by CE.CONT_ID)
   CE
ON S.CONT_ID = CE.CONT_ID
LEFT JOIN PERSONNAME PN
ON S.CONT_ID = PN.CONT_ID AND PN.NAME_USAGE_TP_CD = 1
LEFT JOIN CDPREFIXNAMETP PFXCD
ON PN.PREFIX_NAME_TP_CD = PFXCD.PREFIX_NAME_TP_CD
LEFT JOIN PERSON PER
ON S.CONT_ID = PER.CONT_ID
LEFT JOIN IDENTIFIER NPI
ON S.CONT_ID = NPI.CONT_ID AND NPI.ID_TP_CD = '1000001'
LEFT JOIN IDENTIFIER SSN
ON S.CONT_ID = SSN.CONT_ID AND SSN.ID_TP_CD = '1'
LEFT JOIN 
(
SELECT LG.CONT_ID, A.ADDR_LINE_ONE, A.ADDR_LINE_TWO, A.CITY_NAME, CDSTATE.NAME AS STATE, A.POSTAL_CODE
FROM LOCATIONGROUP LG
INNER JOIN ADDRESSGROUP AG
ON LG.LOCATION_GROUP_ID = AG.LOCATION_GROUP_ID AND AG.ADDR_USAGE_TP_CD = 1
INNER JOIN ADDRESS A
ON AG.ADDRESS_ID = A.ADDRESS_ID
INNER JOIN CDPROVSTATETP CDSTATE
ON A.PROV_STATE_TP_CD = CDSTATE.PROV_STATE_TP_CD) ADDRESS
ON S.CONT_ID = ADDRESS.CONT_ID
LEFT JOIN
(
SELECT LG.CONT_ID, CM.REF_NUM AS HOMEPHONE
FROM LOCATIONGROUP LG
INNER JOIN CONTACTMETHODGROUP CMG
ON LG.LOCATION_GROUP_ID = CMG.LOCATION_GROUP_ID
INNER JOIN CONTACTMETHOD CM
ON CMG.CONTACT_METHOD_ID = CM.CONTACT_METHOD_ID AND CMG.CONT_METH_TP_CD = 1
) HOMEPHONE
ON S.CONT_ID = HOMEPHONE.CONT_ID
LEFT JOIN
(
SELECT LG.CONT_ID, CM.REF_NUM AS BUSINESS_EMAIL
FROM LOCATIONGROUP LG
INNER JOIN CONTACTMETHODGROUP CMG
ON LG.LOCATION_GROUP_ID = CMG.LOCATION_GROUP_ID
INNER JOIN CONTACTMETHOD CM
ON CMG.CONTACT_METHOD_ID = CM.CONTACT_METHOD_ID AND CMG.CONT_METH_TP_CD = 6
) BUSINESS_EMAIL
ON S.CONT_ID = BUSINESS_EMAIL.CONT_ID

LEFT JOIN IDENTIFIER DL
ON S.CONT_ID = DL.CONT_ID AND DL.ID_TP_CD = '3'
LEFT JOIN
(select STLIC.CONT_ID, listagg(STLIC.REF_NUM,',') within group( order by STLIC.REF_NUM ) AS STLICS
  from IDENTIFIER STLIC
  WHERE STLIC.ID_TP_CD = '1000004'
  group by STLIC.CONT_ID
) STLICS
ON S.CONT_ID = STLICS.CONT_ID
  LEFT JOIN IDENTIFIER EMP_ID
ON S.CONT_ID = EMP_ID.CONT_ID AND EMP_ID.ID_TP_CD = '1000024'
LEFT JOIN IDENTIFIER UNIV_ID
ON S.CONT_ID = UNIV_ID.CONT_ID AND UNIV_ID.ID_TP_CD = '1000002'
LEFT JOIN IDENTIFIER UPIN
ON S.CONT_ID = UPIN.CONT_ID AND UPIN.ID_TP_CD = '1000003'








INNER JOIN 
(select CONT_ID, listagg(SRC_SUS.NAME || ':' ||CE_SUS.ADMIN_CLIENT_ID,',') within group( order by SRC_SUS.NAME || ':' ||CE_SUS.ADMIN_CLIENT_ID ) AS SOURCES
  from CONTEQUIV CE_SUS
  INNER JOIN CDADMINSYSTP SRC_SUS
  ON CE_SUS.ADMIN_SYS_TP_CD = SRC_SUS.ADMIN_SYS_TP_CD
  group by CE_SUS.CONT_ID)
   CE_SUS
ON S.SUSPECT_CONT_ID = CE_SUS.CONT_ID
LEFT JOIN PERSONNAME PN_SUS
ON S.SUSPECT_CONT_ID = PN_SUS.CONT_ID AND PN_SUS.NAME_USAGE_TP_CD = 1
LEFT JOIN CDPREFIXNAMETP PFXCD_SUS
ON PN_SUS.PREFIX_NAME_TP_CD = PFXCD_SUS.PREFIX_NAME_TP_CD
LEFT JOIN PERSON PER_SUS
ON S.SUSPECT_CONT_ID = PER_SUS.CONT_ID
LEFT JOIN IDENTIFIER NPI_SUS
ON S.SUSPECT_CONT_ID = NPI_SUS.CONT_ID AND NPI_SUS.ID_TP_CD = '1000001'
LEFT JOIN IDENTIFIER SSN_SUS
ON S.SUSPECT_CONT_ID = SSN_SUS.CONT_ID AND SSN_SUS.ID_TP_CD = '1'
LEFT JOIN 
(
SELECT LG_SUS.CONT_ID, A_SUS.ADDR_LINE_ONE, A_SUS.ADDR_LINE_TWO, A_SUS.CITY_NAME, CDSTATE_SUS.NAME AS STATE, A_SUS.POSTAL_CODE
FROM LOCATIONGROUP LG_SUS
INNER JOIN ADDRESSGROUP AG_SUS
ON LG_SUS.LOCATION_GROUP_ID = AG_SUS.LOCATION_GROUP_ID AND AG_SUS.ADDR_USAGE_TP_CD = 1
INNER JOIN ADDRESS A_SUS
ON AG_SUS.ADDRESS_ID = A_SUS.ADDRESS_ID
INNER JOIN CDPROVSTATETP CDSTATE_SUS
ON A_SUS.PROV_STATE_TP_CD = CDSTATE_SUS.PROV_STATE_TP_CD) ADDRESS_SUS
ON S.SUSPECT_CONT_ID = ADDRESS_SUS.CONT_ID
LEFT JOIN
(
SELECT LG_SUS.CONT_ID, CM_SUS.REF_NUM AS HOMEPHONE
FROM LOCATIONGROUP LG_SUS
INNER JOIN CONTACTMETHODGROUP CMG_SUS
ON LG_SUS.LOCATION_GROUP_ID = CMG_SUS.LOCATION_GROUP_ID
INNER JOIN CONTACTMETHOD CM_SUS
ON CMG_SUS.CONTACT_METHOD_ID = CM_SUS.CONTACT_METHOD_ID AND CMG_SUS.CONT_METH_TP_CD = 1
) HOMEPHONE_SUS
ON S.SUSPECT_CONT_ID = HOMEPHONE_SUS.CONT_ID
LEFT JOIN
(
SELECT LG_SUS.CONT_ID, CM_SUS.REF_NUM AS BUSINESS_EMAIL
FROM LOCATIONGROUP LG_SUS
INNER JOIN CONTACTMETHODGROUP CMG_SUS
ON LG_SUS.LOCATION_GROUP_ID = CMG_SUS.LOCATION_GROUP_ID
INNER JOIN CONTACTMETHOD CM_SUS
ON CMG_SUS.CONTACT_METHOD_ID = CM_SUS.CONTACT_METHOD_ID AND CMG_SUS.CONT_METH_TP_CD = 6
) BUSINESS_EMAIL_SUS
ON S.SUSPECT_CONT_ID = BUSINESS_EMAIL_SUS.CONT_ID

LEFT JOIN IDENTIFIER DL_SUS
ON S.SUSPECT_CONT_ID = DL_SUS.CONT_ID AND DL_SUS.ID_TP_CD = '3'
LEFT JOIN
(select STLIC_SUS.CONT_ID, listagg(STLIC_SUS.REF_NUM,',') within group( order by STLIC_SUS.REF_NUM ) AS STLICS
  from IDENTIFIER STLIC_SUS
  WHERE STLIC_SUS.ID_TP_CD = '1000004'
  group by STLIC_SUS.CONT_ID
) STLICS_SUS
ON S.SUSPECT_CONT_ID = STLICS_SUS.CONT_ID
  LEFT JOIN IDENTIFIER EMP_ID_SUS
ON S.SUSPECT_CONT_ID = EMP_ID_SUS.CONT_ID AND EMP_ID_SUS.ID_TP_CD = '1000024'
LEFT JOIN IDENTIFIER UNIV_ID_SUS
ON S.SUSPECT_CONT_ID = UNIV_ID_SUS.CONT_ID AND UNIV_ID_SUS.ID_TP_CD = '1000002'
LEFT JOIN IDENTIFIER UPIN_SUS
ON S.SUSPECT_CONT_ID = UPIN_SUS.CONT_ID AND UPIN_SUS.ID_TP_CD = '1000003'


WHERE S.CUR_SUSPECT_TP_CD  = '3' ORDER BY CONT_ID;
